#!/usr/bin/env bash

echo "🔍 Running Nix Flake check..."
nix flake check --all-systems

# Jika perintah di atas gagal (exit code != 0), git akan membatalkan commit
if [ $? -ne 0 ]; then
    echo "❌ Nix flake check failed! Commit aborted."
    exit 1
fi

echo "✅ Nix flake check passed."
exit 0
