# Konfigurasi Bahasa & LSP Helix

# Mengonfigurasi rust-analyzer agar menggunakan Clippy untuk linting/diagnostics
[language-server.rust-analyzer.config]
check = { command = "clippy" }

# Mengonfigurasi Bahasa Rust
[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
