[general]
import = [ "~/.config/alacritty/themes/themes/kanagawa_wave.toml" ]

[window]
opacity = 0.85
blur = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
