{
  # colorschemes.mini-base16 = {
  #   enable = true;
  #   settings = {
  #     use_cterm = true;
  #     plugins = {
  #       default = true;
  #     };
  #     palette = {
  #       base00 = "#292a31"; # bg
  #       base01 = "#2D2D30"; # bg_alt
  #       base02 = "#636f83"; # visual
  #       base03 = "#6C7986"; # comment
  #       base04 = "#9D9D9D"; # fg_dark
  #       base05 = "#FFFFFF"; # fg
  #       base06 = "#D4D4D4"; # fg_alt
  #       base07 = "#FFFFFF"; # fg
  #       base08 = "#67B7A4"; # variable
  #       base09 = "#4EB0CC"; # constant
  #       base0A = "#6BDFFF"; # type
  #       base0B = "#FF8170"; # string
  #       base0C = "#FD8F3F"; # attribute
  #       base0D = "#67B7A4"; # function_name
  #       base0E = "#FF7AB2"; # keyword
  #       base0F = "#D2A8FF"; # purple
  #     };
  #   };
    # luaConfig.post = ''
    #   local colors = {
    #     bg = "#292a31",
    #     bg_alt = "#2D2D30",
    #     bg_dark = "#171717",
    #     bg_light = "#252526",
    #     bg_highlight = "#2D2D30",
    #
    #     fg = "#FFFFFF",
    #     fg_alt = "#D4D4D4",
    #     fg_dark = "#9D9D9D",
    #     fg_darker = "#6C7986",
    #
    #     keyword = "#FF7AB2",
    #     string = "#FF8170",
    #     comment = "#6C7986",
    #     number = "#D9C97C",
    #     boolean = "#FF7AB2",
    #     function_name = "#67B7A4",
    #     variable = "#67B7A4",
    #     constant = "#4EB0CC",
    #     type = "#6BDFFF",
    #     property = "#67B7A4",
    #     parameter = "#D2A8FF",
    #
    #     purple = "#D2A8FF",
    #
    #     preprocessor = "#FF7AB2",
    #     attribute = "#FD8F3F",
    #     operator = "#FFFFFF",
    #     punctuation = "#FFFFFF",
    #
    #     swift_attribute = "#FD8F3F",
    #     objc_directive = "#FF7AB2",
    #
    #     cursor = "#ff5257",
    #     cursor_visual = "#8cd0e3",
    #     cursor_line = "#2D2D30",
    #     selection = "#FF7AB2",
    #     visual = "#636f83",
    #     visualmode_highlight_bg = "#636f83",
    #     search = "#613315",
    #     search_fg = "#FFCC02",
    #
    #     line_number = "#858585",
    #     gutter_bg = "#292a31",
    #
    #     border = "#3E3E42",
    #     separator = "#2D2D30",
    #
    #     status_bg = "#2D2D30",
    #     status_fg = "#CCCCCC",
    #     tab_active_bg = "#292a31",
    #     tab_active_fg = "#FFFFFF",
    #     tab_inactive_bg = "#2D2D30",
    #     tab_inactive_fg = "#969696",
    #
    #     error = "#F14C4C",
    #     warning = "#F1C232",
    #     info = "#0099FF",
    #     hint = "#4EB0CC",
    #
    #     git_add = "#67B7A4",
    #     git_change = "#F1C232",
    #     git_delete = "#F14C4C",
    #     git_ignored = "#6C7986",
    #
    #     diff_add = "#263E1C",
    #     diff_add_fg = "#67B7A4",
    #     diff_delete = "#3E1F1C",
    #     diff_delete_fg = "#F14C4C",
    #     diff_change = "#3E3B1C",
    #     diff_change_fg = "#F1C232",
    #
    #     todo = "#F1C232",
    #     fixme = "#F14C4C",
    #     note = "#0099FF",
    #
    #     pmenu_bg = "#454167",
    #     pmenu_fg = "#CCCCCC",
    #     pmenu_sel_bg = "#FF7AB2",
    #     pmenu_sel_fg = "#FFFFFF",
    #     pmenu_scrollbar = "#3E3E42",
    #
    #     scrollbar_thumb = "#686868",
    #
    #     fold_bg = "#2D2D30",
    #     fold_fg = "#969696",
    #
    #     match_paren = "#0099FF",
    #
    #     inc_search = "#094771",
    #
    #     spell_bad = "#F14C4C",
    #     spell_cap = "#F1C232",
    #     spell_rare = "#0099FF",
    #     spell_local = "#67B7A4",
    #
    #     debug_breakpoint = "#E51400",
    #     debug_current_line = "#2D5016",
    #
    #     terminal_black = "#292a31",
    #     terminal_red = "#F14C4C",
    #     terminal_green = "#67B7A4",
    #     terminal_yellow = "#F1C232",
    #     terminal_blue = "#6BDFFF",
    #     terminal_magenta = "#FF7AB2",
    #     terminal_cyan = "#4EB0CC",
    #     terminal_white = "#FFFFFF",
    #
    #     terminal_bright_black = "#6C7986",
    #     terminal_bright_red = "#FF6B6B",
    #     terminal_bright_green = "#5AC8FA",
    #     terminal_bright_yellow = "#FFD60A",
    #     terminal_bright_blue = "#007AFF",
    #     terminal_bright_magenta = "#AF52DE",
    #     terminal_bright_cyan = "#40E0D0",
    #     terminal_bright_white = "#FFFFFF",
    #   }
    #
    #   local highlights = {
    #     Normal = { fg = colors.fg, bg = colors.bg },
    #     NormalFloat = { fg = colors.fg, bg = colors.bg_light },
    #     NormalNC = { fg = colors.fg, bg = colors.bg },
    #     Cursor = { fg = colors.bg, bg = colors.cursor },
    #     CursorInsert = { fg = colors.bg, bg = colors.cursor },
    #     CursorVisual = { fg = colors.bg, bg = colors.cursor_visual },
    #     CursorReplace = { fg = colors.bg, bg = colors.cursor },
    #     CursorCommand = { fg = colors.bg, bg = colors.cursor },
    #     lCursor = { fg = colors.bg, bg = colors.cursor },
    #     CursorLine = { bg = colors.cursor_line },
    #     CursorLineNr = { fg = colors.cursor, bold = true, underline = true },
    #     CursorColumn = { bg = colors.cursor_line },
    #     LineNr = { fg = colors.line_number, bg = colors.gutter_bg },
    #     SignColumn = { bg = colors.gutter_bg },
    #     FoldColumn = { fg = colors.line_number, bg = colors.gutter_bg },
    #     Visual = { bg = colors.visualmode_highlight_bg },
    #     VisualNOS = { bg = colors.visualmode_highlight_bg },
    #     Search = { fg = colors.search_fg, bg = colors.search },
    #     IncSearch = { fg = colors.fg, bg = colors.inc_search },
    #     CurSearch = { fg = colors.search_fg, bg = colors.search },
    #     WinSeparator = { fg = colors.separator },
    #     VertSplit = { fg = colors.separator },
    #     StatusLine = { fg = colors.status_fg, bg = colors.status_bg },
    #     StatusLineNC = { fg = colors.fg_dark, bg = colors.status_bg },
    #     TabLine = { fg = colors.tab_inactive_fg, bg = colors.tab_inactive_bg },
    #     TabLineFill = { bg = colors.tab_inactive_bg },
    #     TabLineSel = { fg = colors.tab_active_fg, bg = colors.tab_active_bg, bold = true },
    #     FloatBorder = { fg = colors.border, bg = colors.bg_light },
    #     FloatTitle = { fg = colors.function_name, bg = colors.bg_light, bold = true },
    #     FloatFooter = { fg = colors.fg_dark, bg = colors.bg_light },
    #     Terminal = { fg = colors.fg, bg = colors.bg },
    #     TerminalNormal = { fg = colors.fg, bg = colors.bg },
    #     TerminalNormalFloat = { fg = colors.fg, bg = colors.bg },
    #     TermCursor = { fg = colors.bg, bg = colors.cursor },
    #     TermCursorNC = { fg = colors.bg, bg = colors.cursor },
    #     Pmenu = { fg = colors.pmenu_fg, bg = colors.pmenu_bg },
    #     PmenuSel = { fg = colors.pmenu_sel_fg, bg = colors.pmenu_sel_bg },
    #     PmenuSbar = { bg = colors.pmenu_scrollbar },
    #     PmenuThumb = { bg = colors.scrollbar_thumb },
    #     CmpItemAbbr = { fg = colors.pmenu_fg },
    #     CmpItemAbbrDeprecated = { fg = colors.fg_dark, strikethrough = true },
    #     CmpItemAbbrMatch = { fg = colors.function_name, bold = true },
    #     CmpItemAbbrMatchFuzzy = { fg = colors.function_name, bold = true },
    #     CmpItemKind = { fg = colors.type, bold = true },
    #     CmpItemMenu = { fg = colors.fg_dark, italic = true },
    #     CmpItemKindText = { fg = colors.fg },
    #     CmpItemKindMethod = { fg = colors.function_name },
    #     CmpItemKindFunction = { fg = colors.function_name },
    #     CmpItemKindConstructor = { fg = colors.function_name },
    #     CmpItemKindField = { fg = colors.property },
    #     CmpItemKindVariable = { fg = colors.variable },
    #     CmpItemKindClass = { fg = colors.type },
    #     CmpItemKindInterface = { fg = colors.type },
    #     CmpItemKindModule = { fg = colors.type },
    #     CmpItemKindProperty = { fg = colors.property },
    #     CmpItemKindUnit = { fg = colors.constant },
    #     CmpItemKindValue = { fg = colors.constant },
    #     CmpItemKindEnum = { fg = colors.type },
    #     CmpItemKindKeyword = { fg = colors.keyword },
    #     CmpItemKindSnippet = { fg = colors.string },
    #     CmpItemKindColor = { fg = colors.string },
    #     CmpItemKindFile = { fg = colors.fg },
    #     CmpItemKindReference = { fg = colors.fg },
    #     CmpItemKindFolder = { fg = colors.function_name },
    #     CmpItemKindEnumMember = { fg = colors.constant },
    #     CmpItemKindConstant = { fg = colors.constant },
    #     CmpItemKindStruct = { fg = colors.type },
    #     CmpItemKindEvent = { fg = colors.function_name },
    #     CmpItemKindOperator = { fg = colors.operator },
    #     CmpItemKindTypeParameter = { fg = colors.parameter },
    #     ScrollbarHandle = { bg = colors.scrollbar_thumb },
    #     Folded = { fg = colors.fold_fg, bg = colors.fold_bg },
    #     MatchParen = { fg = colors.match_paren, bold = true },
    #     ErrorMsg = { fg = colors.error },
    #     WarningMsg = { fg = colors.warning },
    #     ModeMsg = { fg = colors.fg },
    #     MoreMsg = { fg = colors.info },
    #     Question = { fg = colors.info },
    #     Directory = { fg = colors.function_name },
    #     Conceal = { fg = colors.fg_dark },
    #     NonText = { fg = colors.fg_darker },
    #     EndOfBuffer = { fg = colors.bg },
    #     SpecialKey = { fg = colors.fg_darker },
    #     WildMenu = { fg = colors.pmenu_sel_fg, bg = colors.pmenu_sel_bg },
    #     ColorColumn = { bg = colors.bg_highlight },
    #     SpellBad = { fg = colors.spell_bad, undercurl = true },
    #     SpellCap = { fg = colors.spell_cap, undercurl = true },
    #     SpellRare = { fg = colors.spell_rare, undercurl = true },
    #     SpellLocal = { fg = colors.spell_local, undercurl = true },
    #     DiagnosticError = { fg = colors.error },
    #     DiagnosticWarn = { fg = colors.warning },
    #     DiagnosticInfo = { fg = colors.info },
    #     DiagnosticHint = { fg = colors.hint },
    #     DiagnosticVirtualTextError = { fg = colors.error },
    #     DiagnosticVirtualTextWarn = { fg = colors.warning },
    #     DiagnosticVirtualTextInfo = { fg = colors.info },
    #     DiagnosticVirtualTextHint = { fg = colors.hint },
    #     DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
    #     DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warning },
    #     DiagnosticUnderlineInfo = { undercurl = true, sp = colors.info },
    #     DiagnosticUnderlineHint = { undercurl = true, sp = colors.hint },
    #     QuickFixLine = { bg = colors.bg_highlight },
    #     Title = { fg = colors.function_name, bold = true },
    #     debugPC = { bg = colors.debug_current_line },
    #     debugBreakpoint = { fg = colors.debug_breakpoint, bold = true },
    #     Comment = { fg = colors.comment, italic = true },
    #     Constant = { fg = colors.constant },
    #     String = { fg = colors.string },
    #     Character = { fg = colors.string },
    #     Number = { fg = colors.number },
    #     Boolean = { fg = colors.boolean, bold = true },
    #     Float = { fg = colors.number },
    #     Identifier = { fg = colors.fg },
    #     Function = { fg = colors.type },
    #     Statement = { fg = colors.keyword, bold = true },
    #     Conditional = { fg = colors.keyword, bold = true },
    #     Repeat = { fg = colors.keyword, bold = true },
    #     Label = { fg = colors.keyword, bold = true },
    #     Operator = { fg = colors.operator },
    #     Keyword = { fg = colors.keyword, bold = true },
    #     Exception = { fg = colors.keyword, bold = true },
    #     PreProc = { fg = colors.preprocessor, bold = true },
    #     Include = { fg = colors.preprocessor, bold = true },
    #     Define = { fg = colors.preprocessor, bold = true },
    #     Macro = { fg = colors.preprocessor, bold = true },
    #     PreCondit = { fg = colors.preprocessor, bold = true },
    #     Type = { fg = colors.type },
    #     StorageClass = { fg = colors.keyword, bold = true },
    #     Structure = { fg = colors.type },
    #     Typedef = { fg = colors.type },
    #     Special = { fg = colors.attribute },
    #     SpecialChar = { fg = colors.string },
    #     Tag = { fg = colors.keyword, bold = true },
    #     Delimiter = { fg = colors.punctuation },
    #     SpecialComment = { fg = colors.comment, bold = true },
    #     Debug = { fg = colors.error },
    #     Underlined = { fg = colors.info, underline = true },
    #     Ignore = { fg = colors.fg_darker },
    #     Error = { fg = colors.error, bold = true },
    #     Todo = { fg = colors.todo, bold = true },
    #     htmlTag = { fg = colors.keyword, bold = true },
    #     htmlEndTag = { fg = colors.keyword, bold = true },
    #     htmlTagName = { fg = colors.keyword, bold = true },
    #     htmlArg = { fg = colors.property },
    #     htmlString = { fg = colors.string },
    #     cssTagName = { fg = colors.keyword, bold = true },
    #     cssClassName = { fg = colors.function_name },
    #     cssIdentifier = { fg = colors.function_name },
    #     cssProp = { fg = colors.property },
    #     cssValueLength = { fg = colors.number },
    #     cssValueNumber = { fg = colors.number },
    #     cssColor = { fg = colors.number },
    #     cssFunction = { fg = colors.type },
    #     javaScriptFunction = { fg = colors.keyword, bold = true },
    #     javaScriptIdentifier = { fg = colors.fg },
    #     javaScriptMember = { fg = colors.property },
    #     javaScriptNumber = { fg = colors.number },
    #     javaScriptNull = { fg = colors.boolean, bold = true },
    #     javaScriptUndefined = { fg = colors.boolean, bold = true },
    #     jsxTag = { fg = colors.keyword, bold = true },
    #     jsxTagName = { fg = colors.keyword, bold = true },
    #     jsxAttrib = { fg = colors.property },
    #     jsxString = { fg = colors.string },
    #     jsxComponentName = { fg = colors.type },
    #     pythonBuiltin = { fg = colors.type },
    #     pythonException = { fg = colors.type },
    #     pythonDecorator = { fg = colors.attribute },
    #     pythonDecoratorName = { fg = colors.attribute },
    #     luaFunction = { fg = colors.keyword, bold = true },
    #     luaTable = { fg = colors.fg },
    #     luaIn = { fg = colors.keyword, bold = true },
    #     jsonKeyword = { fg = colors.property },
    #     jsonString = { fg = colors.string },
    #     jsonNumber = { fg = colors.number },
    #     jsonBoolean = { fg = colors.boolean, bold = true },
    #     jsonNull = { fg = colors.boolean, bold = true },
    #     diffAdded = { fg = colors.diff_add_fg, bg = colors.diff_add },
    #     diffRemoved = { fg = colors.diff_delete_fg, bg = colors.diff_delete },
    #     diffChanged = { fg = colors.diff_change_fg, bg = colors.diff_change },
    #     diffFile = { fg = colors.function_name },
    #     diffNewFile = { fg = colors.git_add },
    #     diffOldFile = { fg = colors.git_delete },
    #     diffLine = { fg = colors.info },
    #     gitcommitComment = { fg = colors.comment },
    #     gitcommitUnmerged = { fg = colors.git_change },
    #     gitcommitOnBranch = { fg = colors.fg },
    #     gitcommitBranch = { fg = colors.function_name },
    #     gitcommitDiscardedType = { fg = colors.git_delete },
    #     gitcommitSelectedType = { fg = colors.git_add },
    #     gitcommitHeader = { fg = colors.fg },
    #     gitcommitUntrackedFile = { fg = colors.git_ignored },
    #     gitcommitDiscardedFile = { fg = colors.git_delete },
    #     gitcommitSelectedFile = { fg = colors.git_add },
    #     gitcommitUnmergedFile = { fg = colors.git_change },
    #     gitcommitFile = { fg = colors.fg },
    #     vimCommand = { fg = colors.keyword, bold = true },
    #     vimFunction = { fg = colors.fg },
    #     vimUserFunc = { fg = colors.fg },
    #     vimVariable = { fg = colors.fg },
    #     vimOption = { fg = colors.property },
    #     vimHiGroup = { fg = colors.type },
    #     vimGroup = { fg = colors.type },
    #     vimSynType = { fg = colors.type },
    #   }
    #
    #   for group, opts in pairs(highlights) do
    #     vim.api.nvim_set_hl(0, group, opts)
    #   end
    # '';
  # };

  plugins.mini-colors = {
    enable = true;
    luaConfig.post = ''
      require('mini.colors')
        .get_colorscheme()
        :resolve_links()
        :add_transparency({
          general = true,
          float = false,
          statuscolumn = false,
          statusline = true,
          tabline = false,
          winbar = false,
        })
        :apply()
    '';
  };
}
